version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  redis:
    image: redis
    volumes:
      - redis_data:/var/lib/redis/data

  web:
    build: ./app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: password
      REDIS_URL: redis://redis:6379/12
    cap_add:
      - SYS_ADMIN # Makes it possible to run Puppeteer
    depends_on:
      - db
      - redis

  sidekiq:
    image: critical_web:latest
    volumes:
      - ./app:/app
    command: bundle exec sidekiq
    environment:
      POSTGRES_PASSWORD: password
      REDIS_URL: redis://redis:6379/12
    cap_add:
      - SYS_ADMIN # Makes it possible to run Puppeteer
    depends_on:
      - db
      - redis

  wp_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
    volumes:
      - wp_db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php7.4-apache
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: wp_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp:/var/www/html
    depends_on:
      - wp_db

volumes:
  db_data: {}
  redis_data: {}
  wp_db_data: {}
